###############################################################################
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
###############################################################################

FROM @@DockerBase@@/debootstrap-wheezy

VOLUME	["/var/cache/apt-cacher-ng"]

RUN \
	apt-get update \
	&& apt-get install -y apt-cacher-ng \
	&& apt-get clean \
	&& rm /var/lib/apt/* /var/cache/apt/archives/* /var/cache/apt/* 2>/dev/null || true \
	&& true

EXPOSE	3142

CMD     chmod 777 /var/cache/apt-cacher-ng && /etc/init.d/apt-cacher-ng start && tail -f /var/log/apt-cacher-ng/*

